### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by appyschool** [facetec/cordova-plugin-zoom-sdk#1]
* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 18 declared in library [:zoom-authentication:]   \platforms\android\build\intermediates\exploded-aar\zoom-authentication\AndroidManifest.xml
        Suggestion: use tools:overrideLibrary="com.facetec.zoom.sdk" to force usage

**Comment by appyschool** [comment]
After setting the minimum SDK to 18, resulting in to below error 

Execution failed for task ':compileDebugJavaWithJavac'.
> Could not expand ZIP  'UserFilePath\build\intermediates\exploded-aar\zoom-authentication\jars\classes.jar'.

**Comment by facetec** [comment]
Hello @appyschool.  Were you building on a Windows machine?  If so, try the latest version (pushed yesterday) and it might fix the issue.  If you're not on Windows or the latest release doesn't fix the issue, please provide some more detailed error logs so that I can try to figure out the issue.

Thanks,
Greg Perez

**Comment by appyschool** [comment]
Thanks for the quick fix, Now I am able to build the app. But App crashes when we make a call to below API
ZoomAuthentication.enroll(userId, encryptionSecret, onEnrollComplete, onError);

Below error is report after the app crash:

java.lang.RuntimeException: Unable to resume activity {com.ditcos.attendancetracker/com.ditcos.attendancetracker.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1000, result=-1, data=Intent { (has extras) }} to activity {com.ditcos.attendancetracker/com.ditcos.attendancetracker.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3136)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3167)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2514)
	at android.app.ActivityThread.access$1000(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:5523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1000, result=-1, data=Intent { (has extras) }} to activity {com.ditcos.attendancetracker/com.ditcos.attendancetracker.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3738)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3122)
	... 10 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
	at com.facetec.cordova.ZoomAuthentication.onActivityResult(ZoomAuthentication.java:166)
	at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:152)
	at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:358)
	at android.app.Activity.dispatchActivityResult(Activity.java:6508)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3734)
	... 11 more

**Comment by facetec** [comment]
@appyschool Are you able to run the example app (https://github.com/facetec/cordova-example-zoom-sdk) using your app token?

**Comment by plugin-service** [comment]
Contact plugins@snapcommute.com for the upgraded plugin.
